version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_agent
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/ai_agent
      - SESSION_ID=dev-session
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=mistral
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  pgdata: